FROM python:3.11-slim
WORKDIR /app
ENV PYTHONPATH=/app
COPY requirements.txt .
RUN apt-get update && apt-get install -y libxml2-dev libxslt1-dev libjpeg-dev zlib1g-dev && rm -rf /var/lib/apt/lists/* && pip install -r requirements.txt
COPY . .
CMD ["bash","-lc","cd scraper/news_spider && scrapy crawl news_spider"]
